### ISSUE TITLE
Mapping of banking

### ISSUE THREAD

**Issue by yaqiz01** [stanford-ppl/pir#1]
Current strategy of mapping banks across PMUs is mapping the dimension banked along inner loop index into the same PMU. However this is very inefficient in example of SPMV_CRS, where `rowid_sram` is loaded from dram in parallel in 16 banks and read in parallel across outer loop. As a result, 16 PMUs are created for each duplicated. And without analysis on which access belongs to which bank statically, each PMU takes 16 read addresses, which fails splitting. This can be quite common whenever we have something like
```
sram load dram (.... par by 16)
Foreach (par by X){ i =>
    val a = sram(i) // <- parallelized across outer loop indices
    Foreach () { j =>
    }
}

```

A more reasonable way of mapping banks might be mapping the dimension associated with ParSRAM access in spatial IR into the same PMU, in which case all 16 banks of the `rowid_sram` will go into the same PMU. This would require

- compiler
Since unrolling is disabled when PIR is enabled, even with ParSRAMLoad I only see a single index address for each dimension during codegen, which make it impossible to tell along which dimension the ParSRAMLoad is vectorized. Is it possible to have some metadata during unrolling to keep that information or still unroll only for ParSRAM access so I can figure that out by inspecting the indices?
@dkoeplin 

- hardware
To support this in hardware, we need to support the PMU read/write address either coming from a single vector FIFO or 16 scalarFIFO with one address for each bank. Also the PMU needs to be able to connect output of 16 banks separately to 16 scalar output. @raghup17 Do you think this would be too much overhead?

**Comment by raghup17** [comment]
Interesting, I think this is a step in the right direction. We can start by assuming that the overheads are zero. If this improves utilization across the board, we can then figure out a trick to reduce overheads. Also, we can get quantify the overheads better once the layout model is ready.

That said, I have a couple of related points in my mind; hoping to start a discussion here to better understand the tradeoffs:

1. How often does the above access pattern occur? The reason I'm asking is that if this happens mostly with sparse benchmarks, and if we are able to maximize DRAM bandwidth utilization, we can defer this change. The pattern above seems to be more common than just sparse benchmarks, but just wanted to check with you first. Assuming that it is quite common,

2. One future point of concern here is the increase in number of scalar IO; it would look like another vector IO port in the PMU. It would be nice if we can reuse one of the vector IO port to serve this purpose, as we already have 4 of those. I understand that in the general case of above (outer loop is unrolled, sram address could be produced by some unit pipe), the addresses for each lane would be coming from different places on Plasticine, so reusing the vector IO port would need coalescing of some sort. Is there some compiler / hardware trick we can employ to make this happen? Here are some options:

-  For instance, if this pattern is quite common, we can think of having some hierarchy among the scalar CUs such that their collective output can be coalesced and sent to a vector IO.
- Better yet, if possible, can we use 1 PCU for this, where we effectively "pack" 16 such address-generating scalar CUs into one PCU whenever possible? Perhaps if the 16 individual unit pipes are somehow transformed to look like a Foreach, and there is a stream controller around the Foreach and the PMU read?

3. The suggestions in (2) can be complete BS, so perhaps I can work out the details more closely for a few examples. Can you share a couple of benchmarks that have this issue?

**Comment by yaqiz01** [comment]
1. These pattern is not necessarily related to sparse pattern. We can easily turn dot product into the same issue by adding a unit pipe in the inner most loop, which will result in no inner loop indices is banked across any dimension for each sram

2. I'm not sure about packing scalar IOs into vector ones, since each scalar input source might take different number of hops depends on where the producer is mapped to. So the compacting unit will need some FIFOs to first synchronize the scalar input somewhere before they can become a vector input, which means the 16 scalar FIFO must exists somewhere. How's that different from just having them inside PMU? Also having the 16 scalar FIFO is prevision for the worst case where all 16 banks inside a PMU can be used across parallelized outer loop. This likely to be too much since we rarely parallelize outer loop by that much. We can make this number < 16 and if more than 16 banks are needed, they can be mapped across multiple PMUs. 

3. Currently I'm still working on SPMV for other bugs. But I can write another one pretty easily

**Comment by raghup17** [comment]
Follow up on (2): It's different from the PMU in terms of interconnect resource requirement.
