### ISSUE TITLE
Had Troubles Getting Appfix Work on Tucson

### ISSUE THREAD

**Issue by kelayamatoz** [stanford-ppl/pir#5]
***pir app file***: /pir/apps/src/StaticCoreMemFoldGateManualFoldLSTM.scala

***pir commit***: 6dfbe4347ea2b76f19a13b4df2c5acfb4c8ac8f9

***dyspatial***: appfix branch

***machine***: tucson

I was trying to run the appfix-ed LSTM implementation with plastisim; however I got the following errors with prism configuration as described in https://github.com/kelayamatoz/DySpatial/issues/17. 

***Error***: 
sbt -batch "apps/run-main StaticCoreMemFoldGateManualFoldLSTM --cgra+"
PIR Generation: StaticCoreMemFoldGateManualFoldLSTM at /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir
tee: /home/tianzhao/dyspatial-dev/dyspatial/out/StaticCoreMemFoldGateManualFoldLSTM_pirgen.log: No such file or directory
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1g; support was removed in 8.0
Picked up _JAVA_OPTIONS: -Xmx32g -Xss8912k -Xms16g
[info] Loading project definition from /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/project
[info] Set current project to default-5bc199 (in build file:/home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/)
[info] Set current project to apps (in build file:/home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/)
[info] Compiling 1 Scala source to /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/pir/apps/target/scala-2.12/classes...
[info] Running StaticCoreMemFoldGateManualFoldLSTM --mapping=true --stat=true --routing-algo=dor --topo=mesh --net=p2p --row=16 --col=8 --pcu-stages=6 --pmu-stages=4
[pir] args=[--stat=true, --trace=true, --run-psim=true, --psim-timeout=100000000, --net=p2p, --row=16, --col=8, --topo=mesh, --arch=MyDesign, --nn=false, --pattern=checkerboard, --pcu-stage=6, --argin=20, --argout=4, --tokenout=5, --fifo-depth=10, --vc=10, --mapping=true, --stat=true, --routing-algo=dor, --topo=mesh, --net=p2p, --row=16, --col=8, --pcu-stages=6, --pmu-stages=4]
[pir] Output directory set to /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/out/StaticCoreMemFoldGateManualFoldLSTM
[pir] Finishing graph construction for StaticCoreMemFoldGateManualFoldLSTM
[pir] Configuring spade MyDesign ...
New design elapsed time: 1320.405ms
[pir] Finished 00-TestTraversal in 751.606835ms
[pir] Finished 01-ControlPropogation in 7.257231ms
[pir] Finished 02-FringeElaboration in 109.05929ms
[pir] Finished 03-PIRIRDotCodegen to top1.dot in 848.931313ms
[pir] Finished 04-DeadCodeElimination in 1839.200924ms
[pir] Finished 05-ConstantExpressionEvaluation in 592.833915ms
[pir] Finished 06-ControlPropogation in 2.232456ms
[pir] Finished 07-IRCheck in 1474.099977ms
[pir] Finished 08-PIRPrinter to IR1.txt in 525.979192ms
[pir] Finished 09-PIRIRDotCodegen to top2.dot in 480.522091ms
[pir] Finished 10-UnrollingTransformer in 76.057788ms
[pir] Finished 11-PIRIRDotCodegen to top3.dot in 468.484491ms
[pir] Finished 12-CUInsertion in 77.244904ms
[pir] Finished 13-AccessPulling in 3407.704799ms
[pir] Finished 14-DeadCodeElimination in 659.16374ms
[pir] Finished 15-PIRIRDotCodegen to top4.dot in 415.399275ms
[pir] Finished 16-SimpleIRDotCodegen to simple1.dot in 239.478162ms
[pir] Finished 17-AccessLowering in 931.180342ms
[pir] Finished 18-PIRIRDotCodegen to top5.dot in 1347.7854ms
[pir] Finished 19-BankedAccessMerging in 2754.562939ms
[pir] Finished 20-PIRIRDotCodegen to top6.dot in 1211.612031ms
[pir] Finished 21-MemoryAnalyzer in 137.679088ms
[pir] Finished 22-ControllerRuntimeAnalyzer in 242.295698ms
[pir] Finished 23-CUStatistics to stat.json in 344.717054ms
[fail] IgraphPartioner failed: ***CostConstrainFailure(CUMap,CUContainer1884,CUCost(AFGCost(false),MCCost(false),SramSizeCost(131072),SramCost(1),ControlInputCost(0),ScalarInputCost(0),VectorInputCost(1),ControlOutputCost(0),ScalarOutputCost(0),VectorOutputCost(1),StageCost(12),LaneCost(16),OpCost(Set(FixMul, FixAdd))),false)***
[pir] Finished 24-IgraphPartioner in 6753.845936ms
[pir] Finished 25-PIRIRDotCodegen to top7.dot in 1133.045381ms
[pir] Finished 26-SimpleIRDotCodegen to simple2.dot in 275.975954ms
[pir] Finished 27-ControllerDotCodegen to controller1.dot in 2019.453221ms
[warn] 28-RouteThroughElimination not run due to dependency IgraphPartioner not success
[warn] 29-DeadCodeElimination not run due to dependency RouteThroughElimination not success
[pir] Finished 30-ControllerDotCodegen to controller2.dot in 1994.17746ms
[pir] Finished 31-PIRIRDotCodegen to top8.dot in 1117.832707ms
[warn] 32-SimpleIRDotCodegen not run due to dependency RouteThroughElimination not success
[pir] Finished 33-PIRPrinter to IR2.txt in 1150.137925ms
[warn] 34-IRCheck not run due to dependency RouteThroughElimination not success
[warn] 35-ContextInsertion not run due to dependency IgraphPartioner not success
[warn] 36-PIRIRDotCodegen not run due to dependency ContextInsertion not success
[warn] 37-MemoryAnalyzer not run due to dependency ContextInsertion not success
[warn] 38-ControlAllocation not run due to dependency ContextInsertion not success
[warn] 39-ControlRegInsertion not run due to dependency ControlAllocation not success
[warn] 40-MemoryAnalyzer not run due to dependency ControlRegInsertion not success
[pir] Finished 41-PIRIRDotCodegen to top10.dot in 1132.854601ms
[warn] 42-ControlAllocation not run due to dependency MemoryAnalyzer not success
[pir] Finished 43-DeadCodeElimination in 2583.301675ms
[pir] Finished 44-PIRIRDotCodegen to top11.dot in 946.325013ms
[warn] 45-ControlLowering not run due to dependency ControlAllocation not success
[pir] Finished 46-PIRIRDotCodegen to top12.dot in 912.456382ms
[pir] Finished 47-IRCheck in 43.301968ms
[pir] Finished 48-ControllerPrinter to controller.txt in 502.398192ms
[pir] Finished 49-CUStatistics to stat.json in 182.896238ms
[warn] 50-PlastisimTraceCodegen not run due to dependency ControlLowering not success
[warn] 51-PlastisimLinkAnalyzer not run due to dependency ControlLowering not success
[warn] 52-PlastisimCountCheck not run due to dependency PlastisimLinkAnalyzer not success
[warn] 53-PlastisimDotCodegen not run due to dependency PlastisimLinkAnalyzer not success
[pir] Finished 54-ControllerDotCodegen to controller.dot in 1853.723104ms
[pir] Finished 55-PIRIRDotCodegen to top.dot in 1038.992794ms
[pir] Finished 56-SimpleIRDotCodegen to simple.dot in 293.776018ms
[pir] Finished 57-PIRPrinter to IR.txt in 1057.730441ms
[fail] CUPruning failed: CostConstrainFailure: CUContainer1884
CUCost(AFGCost(false),MCCost(false),SramSizeCost(131072),SramCost(1),ControlInputCost(0),ScalarInputCost(0),VectorInputCost(1),ControlOutputCost(0),ScalarOutputCost(0),VectorOutputCost(1),StageCost(12),LaneCost(16),OpCost(Set(FixMul, FixAdd)))
[pir] Finished 58-CUPruning in 4.025993ms
[warn] 59-CUPlacer not run due to dependency CUPruning not success
[warn] 60-CUStatistics not run due to dependency CUPlacer not success
[warn] 61-PIRNetworkDotCodegen not run due to dependency CUPlacer not success
[warn] 62-PIRNetworkDotCodegen not run due to dependency CUPlacer not success
[warn] 63-PIRNetworkDotCodegen not run due to dependency CUPlacer not success
[warn] 64-TerminalCSVCodegen not run due to dependency CUPlacer not success
[warn] 65-LinkCSVCodegen not run due to dependency TerminalCSVCodegen not success
[warn] 66-PlastisimPlacementCodegen not run due to dependency CUPlacer not success
[warn] 67-PlastisimDotCodegen not run due to dependency PlastisimLinkAnalyzer not success
[warn] 68-PlastisimConfigCodegen not run due to dependency CUPlacer not success
[pir] Finished 69-PlastisimDotCodegen to psim.dot in 1005.395206ms

**Comment by yaqiz01** [comment]
SramSizeCost(131072) larger than 64 * 1024 = 65536 words in PMU
