### ISSUE TITLE
plastisim and plastiroute repositories are still private :)

### ISSUE THREAD

**Issue by kammoh** [stanford-ppl/pir#55]
The referenced submodules https://github.com/acrucker/plastisim.git and https://github.com/acrucker/plastiroute.git are still private repositories.

**Comment by yaqiz01** [comment]
Thanks for your interest. Place and route and simulator are not officially released by the owner.

**Comment by kammoh** [comment]
Thank you @yaqiz01 for your prompt reply! I look forward to playing around with the placticine tools when they’re released!
