### ISSUE TITLE
psim fails for an app with LUT

### ISSUE THREAD

**Issue by kelayamatoz** [stanford-ppl/pir#9]
***commit***: 097dacffcab505fa008a126b538fb3e2587f7f40
***app***: TanhResourceTestLUT, TanhResourceTestPieceWiseApprox
I got the following error: 
[command] ln -f /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/mesh_generic.cfg /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/
[psim] /home/tianzhao/dyspatial-dev/simulator/plastisim/plastisim -f /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/config.psim -p /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/final.place -c 100000000 -l B -w 512 -q1
[psim] log in /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/out/TanhResourceTestLUT/psim.log
[error] failed /home/tianzhao/dyspatial-dev/simulator/plastisim/plastisim -f /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/config.psim -p /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/final.place -c 100000000 -l B -w 512 -q1
[fail] PlastisimConfigCodegen failed: Plastisim failed. details in /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/out/TanhResourceTestLUT/psim.log
[pir] Finished 68-PlastisimConfigCodegen to config.psim in 588.417264ms
[pir] Finished 69-PlastisimDotCodegen to psim.dot in 257.32506ms

This is after PIR reported completion of CUPlacer. Seems that this is an issue with psim? Would love to get some guide on this issue. Thanks! 

Full Error Log: 

sbt -batch "apps/run-main TanhResourceTestLUT --cgra+"
PIR Run: TanhResourceTestLUT at /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1g; support was removed in 8.0
Picked up _JAVA_OPTIONS: -Xmx32g -Xss8912k -Xms16g
[info] Loading project definition from /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/project
[info] Set current project to default-5bc199 (in build file:/home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/)
[info] Set current project to apps (in build file:/home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/)
[info] Compiling 1 Scala source to /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/pir/apps/target/scala-2.12/classes...
[info] Running TanhResourceTestLUT
[pir] args=[--stat=true, --trace=true, --run-psim=true, --psim-timeout=100000000, --net=p2p, --row=16, --col=8, --topo=mesh, --arch=MyDesign, --nn=false, --pattern=checkerboard, --pcu-stage=6, --argin=20, --argout=4, --tokenout=5, --fifo-depth=10, --vc=10]
[pir] Output directory set to /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/out/TanhResourceTestLUT
[pir] Finishing graph construction for TanhResourceTestLUT
[pir] Configuring spade MyDesign ...
New design elapsed time: 1799.575ms
[pir] Finished 00-TestTraversal in 414.81124ms
[pir] Finished 01-ControlPropogation in 3.733908ms
[pir] Finished 02-FringeElaboration in 88.499153ms
[pir] Finished 03-PIRIRDotCodegen to top1.dot in 116.949669ms
[pir] Finished 04-DeadCodeElimination in 85.913185ms
[pir] Finished 05-ConstantExpressionEvaluation in 63.028461ms
[pir] Finished 06-ControlPropogation in 1.190132ms
[pir] Finished 07-IRCheck in 22.281283ms
[pir] Finished 08-PIRPrinter to IR1.txt in 77.400879ms
[pir] Finished 09-PIRIRDotCodegen to top2.dot in 55.896118ms
[pir] Finished 10-UnrollingTransformer in 27.372293ms
[pir] Finished 11-PIRIRDotCodegen to top3.dot in 53.431944ms
[pir] Finished 12-CUInsertion in 465.783866ms
[pir] Finished 13-AccessPulling in 79.054157ms
[pir] Finished 14-DeadCodeElimination in 55.423197ms
[pir] Finished 15-PIRIRDotCodegen to top4.dot in 42.57321ms
[pir] Finished 16-SimpleIRDotCodegen to simple1.dot in 65.853525ms
[pir] Finished 17-AccessLowering in 129.788426ms
[pir] Finished 18-PIRIRDotCodegen to top5.dot in 90.019598ms
[pir] Finished 19-BankedAccessMerging in 54.001568ms
[pir] Finished 20-PIRIRDotCodegen to top6.dot in 443.869946ms
[pir] Finished 21-MemoryAnalyzer in 18.158765ms
[pir] Finished 22-ControllerRuntimeAnalyzer in 59.016487ms
[pir] Finished 23-CUStatistics to stat.json in 104.269105ms
[pir] Finished 24-IgraphPartioner in 1282.331601ms
[pir] Finished 25-PIRIRDotCodegen to top7.dot in 56.927295ms
[pir] Finished 26-SimpleIRDotCodegen to simple2.dot in 26.321319ms
[pir] Finished 27-ControllerDotCodegen to controller1.dot in 47.682413ms
[pir] Finished 28-RouteThroughElimination in 452.228452ms
[pir] Finished 29-DeadCodeElimination in 93.612404ms
[pir] Finished 30-ControllerDotCodegen to controller2.dot in 41.700315ms
[pir] Finished 31-PIRIRDotCodegen to top8.dot in 43.758978ms
[pir] Finished 32-SimpleIRDotCodegen to simple3.dot in 20.792685ms
[pir] Finished 33-PIRPrinter to IR2.txt in 94.085666ms
[pir] Finished 34-IRCheck in 4.386728ms
[pir] Finished 35-ContextInsertion in 45.895657ms
[pir] Finished 36-PIRIRDotCodegen to top9.dot in 444.175514ms
[pir] Finished 37-MemoryAnalyzer in 14.323845ms
[pir] Finished 38-ControlAllocation in 586.293151ms
[pir] Finished 39-ControlRegInsertion in 28.704654ms
[pir] Finished 40-MemoryAnalyzer in 19.262365ms
[pir] Finished 41-PIRIRDotCodegen to top10.dot in 191.107681ms
[pir] Finished 42-ControlAllocation in 199.082422ms
[pir] Finished 43-DeadCodeElimination in 782.276947ms
[pir] Finished 44-PIRIRDotCodegen to top11.dot in 399.390315ms
[pir] Finished 45-ControlLowering in 95.12217ms
[pir] Finished 46-PIRIRDotCodegen to top12.dot in 246.837773ms
[pir] Finished 47-IRCheck in 536.534216ms
[pir] Finished 48-ControllerPrinter to controller.txt in 97.644828ms
[pir] Finished 49-CUStatistics to stat.json in 112.942739ms
[command] mkdir -p /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/traces
[command] mkdir -p /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/trace_classes
[trace] /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/bin/run_trace /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/out/TanhResourceTestLUT /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT
[trace] log in /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/out/TanhResourceTestLUT/trace.log
[pir] Finished 50-PlastisimTraceCodegen to gen_trace.scala in 4376.90014ms
[pir] Finished 51-PlastisimLinkAnalyzer in 332.204138ms
[pir] Finished 52-PlastisimCountCheck in 82.099692ms
[pir] Finished 53-PlastisimDotCodegen to psim.dot in 266.647187ms
[pir] Finished 54-ControllerDotCodegen to controller.dot in 91.07586ms
[pir] Finished 55-PIRIRDotCodegen to top.dot in 183.361393ms
[pir] Finished 56-SimpleIRDotCodegen to simple.dot in 56.018539ms
[pir] Finished 57-PIRPrinter to IR.txt in 225.47812ms
[pir] Finished 58-CUPruning in 406.415454ms
[success] CUPlacer succeeded.
[pir] Finished 59-CUPlacer in 93.879467ms
[pir] =========== Post-splitting CU Statistics ==================
[pir]
[pir] number of cus=15
[pir] number of ocu = 3
[pir] - cin (1.00,1.00,1.00) sin (0.00,0.00,0.00) vin (0.00,0.00,0.00)
[pir] - cout (1.00,1.00,1.00) sout (0.00,0.00,0.00) vout (0.00,0.00,0.00)
[pir] - stages (0.00,0.00,0.00)
[pir] number of pcu = 1
[pir] - cin (0.00,0.00,0.00) sin (0.00,0.00,0.00) vin (2.00,2.00,2.00)
[pir] - cout (0.00,0.00,0.00) sout (0.00,0.00,0.00) vout (1.00,1.00,1.00)
[pir] - stages (4.00,4.00,4.00)
[pir] number of dag = 3
[pir] - cin (0.00,0.00,0.00) sin (1.00,1.00,1.00) vin (0.00,0.00,0.00)
[pir] - cout (0.00,0.00,0.00) sout (2.00,2.00,2.00) vout (0.00,0.00,0.00)
[pir] - stages (1.00,1.00,1.00)
[pir] number of pmu = 4
[pir] - cin (0.00,0.25,1.00) sin (0.00,0.00,0.00) vin (1.00,1.00,1.00)
[pir] - cout (0.00,0.00,0.00) sout (0.00,0.50,1.00) vout (0.00,0.50,1.00)
[pir] - stages (0.00,0.75,3.00)
[pir] number of dfg = 3
[pir] - cin (0.00,0.00,0.00) sin (2.00,2.67,3.00) vin (0.00,0.00,0.00)
[pir] - cout (0.00,0.67,1.00) sout (0.00,0.00,0.00) vout (0.00,0.33,1.00)
[pir] - stages (0.00,0.00,0.00)
[pir] number of afg = 1
[pir] - cin (2.00,2.00,2.00) sin (0.00,0.00,0.00) vin (0.00,0.00,0.00)
[pir] - cout (1.00,1.00,1.00) sout (3.00,3.00,3.00) vout (0.00,0.00,0.00)
[pir] - stages (0.00,0.00,0.00)
[pir] compute CU = 4
[pir] memory CU = 4
[pir] mc CU = 3
[pir] Total = 7
[pir] PCU = 8 / 63 (12.70%)
[pir] PMU-comp = 0 / 64 (0.00%)
[pir] PMU-mem = 3 / 64 (4.69%)
[pir] AG-ag = 0 / 32 (0.00%)
[pir] AG-comp = 0 / 32 (0.00%)
[pir] MC = 3 / 32 (9.38%)
[pir] Finished 60-CUStatistics to stat.json in 257.35516ms
[pir] Finished 61-PIRNetworkDotCodegen to control.dot in 95.568712ms
[pir] Finished 62-PIRNetworkDotCodegen to scalar.dot in 87.657476ms
[pir] Finished 63-PIRNetworkDotCodegen to vector.dot in 87.143319ms
[pir] Finished 64-TerminalCSVCodegen to node.csv in 4.554538ms
[pir] Finished 65-LinkCSVCodegen to link.csv in 166.782415ms
[pir] Running 66-PlastisimPlacementCodegen ...
[pir] Finished 66-PlastisimPlacementCodegen to final.place in 149.54184ms
[pir] Finished 67-PlastisimDotCodegen to psim.dot in 235.679122ms
[command] ln -f /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/mesh_generic.cfg /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/
[psim] /home/tianzhao/dyspatial-dev/simulator/plastisim/plastisim -f /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/config.psim -p /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/final.place -c 100000000 -l B -w 512 -q1
[psim] log in /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/out/TanhResourceTestLUT/psim.log
[error] failed /home/tianzhao/dyspatial-dev/simulator/plastisim/plastisim -f /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/config.psim -p /home/tianzhao/dyspatial-dev/simulator/plastisim/configs/gen/TanhResourceTestLUT/final.place -c 100000000 -l B -w 512 -q1
[fail] PlastisimConfigCodegen failed: Plastisim failed. details in /home/tianzhao/dyspatial-dev/spatial-lang-pir/pir/out/TanhResourceTestLUT/psim.log
[pir] Finished 68-PlastisimConfigCodegen to config.psim in 588.417264ms
[pir] Finished 69-PlastisimDotCodegen to psim.dot in 257.32506ms

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last apps/compile:runMain for the full output.
[error] (apps/compile:runMain) Nonzero exit code: 1
[error] Total time: 38 s, completed Aug 14, 2018 9:18:31 PM
mv: cannot stat ‘/home/tianzhao/dyspatial-dev/dyspatial/../{1}.*’: No such file or directory

**Comment by kelayamatoz** [comment]
PIR apps are pushed to the master branch under pir/apps/src/TanhResourceTestLUT.scala and pir/apps/src/TanhResourceTestPieceWiseApprox.scala.

**Comment by yaqiz01** [comment]
This is due to a limitation to trace enabled simulation in plastisim right now that it does not support store request less than a burst size. One burst is 16 words in plasticine. So that means with dense DRAM store, the storePar must be 16. We can talk to @acrucker to see if there's a plan to fix it. You can also try parallelize the store by 16 and see if that fix it. Normally we want to parallelize all DRAM loads and stores by 16 if possible. I see one of your load and one of your store is parallelized by 1.

**Comment by kelayamatoz** [comment]
Got it. Thanks!
